### ISSUE TITLE
Infografia hilos de programacion

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/infografia-de-hilos-22620188Oliverio#3]
[Hilos de Programacion (3).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-22620188Oliverio/files/15126160/Hilos.de.Programacion.3.pdf)

**Comment by Kim-Mendoza3** [comment]
calificacion 17, falto funciones de los hilos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
